export const ActionTypes = {
  FETCH_COINMARKETCAP_DETAILS: 'FETCH_COINMARKETCAP_DETAILS',
  FETCH_COINMARKETCAP_DETAILS_START: 'FETCH_COINMARKETCAP_DETAILS_START',
  FETCH_COINMARKETCAP_DETAILS_SUCCESS: 'FETCH_COINMARKETCAP_DETAILS_SUCCESS',
  FETCH_COINMARKETCAP_DETAILS_ERROR: 'FETCH_COINMARKETCAP_DETAILS_ERROR',
};
