export const strings = {
    USD:'USD',
    QUOTE: 'Quote',
    MAX_SUPPLY: 'Max Supply',
    CIRCULATING_SUPPLY: 'Circulating Supply',
    TOTAL_SUPPLY: 'Total Supply',
    PRICE: 'Price',
    VOLUME_24_HOURS: 'Volume 24 Hours',
    CHANGE_PER_1_HOUR: 'Change % 1 Hour',
    CHANGE_PER_24_HOURS: 'Change % 24 Hours',
    CHANGE_PER_7_DAYS: 'Change % 7 Days',
    MARKET_CAP: 'Market Cap',
    TIME_OUT: 'The request timed out',
    ERROR_DEFAULT_MESSAGE: 'Sorry, something went wrong, please try again later',
    OK: 'OK',
}
